### ISSUE TITLE
Couldn't run Usage through requirement.txt

### ISSUE THREAD

**Issue by Aisimilan** [7eu7d7/ML-Danbooru#4]
(venv) F:\ML-Danbooru>python demo.py --data F:\collapse_ben_train_ml --model_name tresnet_d --num_of_groups 32 --ckpt F:\ML-Danbooru\model --thr 0.7 --image_size 512
xformers not find
Traceback (most recent call last):
  File "F:\ML-Danbooru\demo.py", line 12, in <module>
    from src_files.models import create_model
  File "F:\ML-Danbooru\src_files\models\__init__.py", line 1, in <module>
    from .utils import create_model
  File "F:\ML-Danbooru\src_files\models\utils\__init__.py", line 1, in <module>
    from .factory import create_model
  File "F:\ML-Danbooru\src_files\models\utils\factory.py", line 9, in <module>
    from ..caformer import build_caformer
  File "F:\ML-Danbooru\src_files\models\caformer\__init__.py", line 1, in <module>
    from .ml_caformer import build_caformer
  File "F:\ML-Danbooru\src_files\models\caformer\ml_caformer.py", line 8, in <module>
    from .metaformer_baselines import MetaFormer
  File "F:\ML-Danbooru\src_files\models\caformer\metaformer_baselines.py", line 27, in <module>
    from timm.models.layers.helpers import to_2tuple
ModuleNotFoundError: No module named 'timm.models.layers.helpers'

(venv) F:\ML-Danbooru>pip list
Package            Version
------------------ ---------
certifi            2023.5.7
charset-normalizer 3.1.0
colorama           0.4.6
einops             0.6.1
filelock           3.12.0
fsspec             2023.5.0
huggingface-hub    0.14.1
idna               3.4
inplace-abn        1.1.0
Jinja2             3.1.2
loguru             0.7.0
MarkupSafe         2.1.2
mpmath             1.3.0
networkx           3.1
numpy              1.24.3
packaging          23.1
Pillow             9.5.0
pip                22.2.1
PyYAML             6.0
requests           2.30.0
safetensors        0.3.1
setuptools         63.2.0
sklearn            0.0.post5
sympy              1.12
timm               0.9.2
torch              2.0.1
torchvision        0.15.2
tqdm               4.65.0
typing_extensions  4.5.0
urllib3            2.0.2
win32-setctime     1.1.0

**Comment by M4X1K02** [comment]
'[timm.models.layers moved to timm.layers](https://pypi.org/project/timm/)'
Just change it in the code where it occurrs, so in `metaformer_baselines.py`.
